### ISSUE TITLE
Error when using fs.createReadStream

### ISSUE THREAD

**Issue by KrysD** [KrysD/d3Training#1]
@vallettea, @iOiurson
I tried to create a read stream to load a `.csv` file like we have done during training, but i get an error.   And i dont understand why...
![error](https://cloud.githubusercontent.com/assets/13766508/17171369/bd4dc0f8-53f0-11e6-8767-3ac754543d33.PNG) 
I tried to find a solution on the web but i didn't find anything.

**Comment by bleucitron** [comment]
It is most probable that you are trying to use Node-only functionalities inside a browser.
The purpose of Browserify is to adapt Node's code to a browser context, but some functions aren't allowed by browsers (mainly for security purposes), so Browserify doesn't translate them.
`fs` module is one of those forbidden functionalities, meaning you can only use `fs` server-side.

You're allowed however to read JSON client-side, so you should generate your file as JSON server-side, and read it as JSON client-side.

**Comment by KrysD** [comment]
Ok i understand. Thx @iOiurson  !
